### ISSUE TITLE
interactive-calibrationv2/

### ISSUE THREAD

**Issue by yuyadanyadan** [UTDRobosub/librobosub#1]
Hi 
  I use your code in interactive-calibrationv2 to calibrate my camera with charuco board. I get the result is not good.  Do you know why?  Thank you very much!

**Comment by smo-key** [comment]
Hi @yuyadanyadan,

The code in `interactive-calibrationv2` is very similar to the demo provided in opencv. For a slightly more complex example, you can try https://github.com/opencv/opencv/blob/master/samples/cpp/tutorial_code/calib3d/camera_calibration/camera_calibration.cpp. 

We got good results on a few cameras using `interactive-calibrationv2` (some wide angle, some not) after taking 15 or so images of the default charuco board in several positions.

A couple tips to ensure you get good images:
- Ensure the charuco board is mounted on an absolutely flat surface and still. We used a carefully constructed cardboard box and tape.
- Make sure the lighting is good and images look clear (and not blurry) through the app.
- You will rarely ever get good results before the 12th image or so. For a while, the image may look distorted and you will need to keep taking images.
- Do not take too many images. If after 30 images, the results are still not good, restart.
- If all else fails, try a few times. We only got good results after several attempts.
